-- Q1. What is total revenue generated by male vs female customer?

SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than averaage purchase amount?

SELECT customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount>=(SELECT AVG(purchase_amount) From customer);

--Q3. Which are the top 5 products with the highest average review rating.

select item_purchased, Round(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4. Compare the average Purchase amount between the Standard and Express Shipping
select shipping_type, ROUND(avg(purchase_amount),2) AS avg_purchase_amount
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spends more? Compare average spend and total revenue btw subscribers and non-subscriber?
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/count(*),2) AS discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Segment customers into New, Returning, and loyal based on their total number of previous purchases, and show the count of each segment 
with customer_type as (
select customer_id, previous_purchases,
Case 
     WHEN previous_purchases =1 Then 'new'
	 when previous_purchases BETWEEN 2 and 10 then 'Returning'
	 else 'Loyal'
	 end as customer_segment
from customer
)

select customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank<=3;

--Q9. Are customer who are repeat buyers(more than 5 previous purchase ) are likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

--Q10. What is the revenue contibution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc